### ISSUE TITLE
Updated README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [Olanetsoft/article-idea-generator#38]
I really like your project !!!
Made a minor edit

### Before:
![image](https://user-images.githubusercontent.com/121221252/215655274-75fbd398-2a8c-4fe5-9568-c915f502232a.png)

### After:
![image](https://user-images.githubusercontent.com/121221252/215655300-c0c21ab7-341a-49cf-b357-048e2e1ad3d6.png)

**Comment by the-amazing-atharva** [comment]
Should I send a PR ?

**Comment by Olanetsoft** [comment]
Yes please @the-amazing-atharva

**Comment by the-amazing-atharva** [comment]
Sure
